version: '3.1'
services:
  odoo_web:
    image: sparkyideainc/odoo:16.0-arm64-dev
    container_name: odoo_web
    depends_on:
      - odoo_db
    environment:
      - DB_HOST=odoo_db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=CHANGEME
    ports:
      - "8069:8069"
      - "8071:8071"
    volumes:
      - odoo-web-data:/opt/odoo/data
      - ./my_odoo/config:/etc/odoo
      - ./my_odoo/custom_addons/:/opt/odoo/custom_addons
    command: ${MODE:-production}
  odoo_db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=CHANGEME
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
